server:
  port: 5001

spring:
  jpa:
    hibernate:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      ddl-auto: "update"
      show-sql: "true"
  datasource:
    url: "jdbc:postgresql://localhost:5432/my_database"
    username: "postgres"
    password: "root"
    initialization-mode: "always"
    initialize: "true"